[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
der = { workspace = true }
env_logger = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
pkix = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vsock = { workspace = true }