[package]
name = "client"
description = "A program used to establish trust on the machine it runs and initialize the a baremetal sev-snp VM to start a trusted workload."
version = "0.1.0"
authors = ["Fortanix, Inc."]
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/fortanix/attestation"

[dependencies]
der = { workspace = true }
env_logger = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
pkix = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vsock = { workspace = true }