[package]
name = "client"
description = "A program used to establish trust on the machine it runs and initialize the a baremetal sev-snp VM to start a trusted workload."
version = "0.1.0"
authors = ["Fortanix, Inc."]
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/fortanix/attestation"

[dependencies]
attestation = { path = "../attestation", features = ["tdx-guest", "nvidia-evidence", "sev-guest", "tpm-snp-evidence", "tpm-snp-pkix-compat"] }
der = { workspace = true }
em-node-agent-client = { workspace = true }
env_logger = { workspace = true }
ftx-cert-build = { workspace = true, features = ["rsa", "mbedtls_adapter"] }
hyper = { workspace = true }
log = { workspace = true }
mbedtls = { workspace = true, features = ["rdrand"] }
pkix = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
vsock = { workspace = true }

[[example]]
name = "attestation-client-sevsnp"
path = "src/examples/attestation-client-sevsnp.rs"

[[example]]
name = "attestation-client-tdx"
path = "src/examples/attestation-client-tdx.rs"
