/* Copyright (c) Fortanix, Inc.
|* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
|* the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#[cfg(feature = "nvidia-evidence")]
pub mod evidence;

#[cfg(feature = "nvidia-evidence")]
pub use evidence::error::GpuError;
use serde::{Deserialize, Serialize};

/// This struct holds the evidence needed to perform
/// remote attestation for Nvidia GPUs.
#[derive(Serialize, Deserialize, Debug)]
pub struct NvidiaEvidence {
    /// The GPU attestation certificate chain. The last certificate in this list is expected to
    /// be the self-signed NVIDIA Device Identity CA
    pub certificates: Vec<u8>,

    /// The attestation report generated by the GPU based on a provided nonce.
    pub report: Vec<u8>,
}
