/* Copyright (c) Fortanix, Inc.
|* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
|* the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/. */

pub mod csr_format;

#[cfg(feature = "nvidia-evidence")]
pub mod evidence;

#[cfg(feature = "nvidia-evidence")]
pub use evidence::error::GpuError;

use b64_ct::FromBase64;
use der::asn1::OctetString;
use der::{Decode, Document};
use pkix::pem::{der_to_pem, PEM_CERTIFICATE};
use serde::{Deserialize, Serialize};

use csr_format::NvidiaAttestationV1;

pub fn pems_to_der(pems: &[u8]) -> Result<Vec<Vec<u8>>, der::Error> {
    let content = std::str::from_utf8(pems)?;

    content
        .split("-----BEGIN CERTIFICATE-----")
        .filter(|s| !s.is_empty())
        .map(|cert| {
            let cert_part = cert
                .split("-----END CERTIFICATE-----")
                .next()
                .ok_or_else(|| der::Error::from(der::ErrorKind::Failed))?;

            let base64_data = cert_part
                .lines()
                .filter(|line| !line.is_empty())
                .collect::<String>();

            base64_data
                .from_base64()
                .map_err(|_| der::Error::from(der::ErrorKind::Failed))
        })
        .collect()
}

/// This struct holds the evidence needed to perform
/// remote attestation for Nvidia GPUs.
#[derive(Serialize, Deserialize, Debug)]
pub struct NvidiaEvidence {
    /// The GPU attestation certificate chain. The last certificate in this list is expected to
    /// be the self-signed NVIDIA Device Identity CA
    pub certificates: Vec<u8>,

    /// The attestation report generated by the GPU based on a provided nonce.
    pub report: Vec<u8>,
}

impl TryFrom<&NvidiaEvidence> for NvidiaAttestationV1 {
    type Error = der::Error;

    fn try_from(evidence: &NvidiaEvidence) -> der::Result<Self> {
        let certificates = pems_to_der(&evidence.certificates)?
            .iter()
            .map(|cert| Document::from_der(cert))
            .collect::<der::Result<_>>()?;

        Ok(NvidiaAttestationV1 {
            attestation_report: OctetString::new(&*evidence.report)?,
            certificates,
        })
    }
}

impl TryFrom<NvidiaAttestationV1> for NvidiaEvidence {
    type Error = String;

    fn try_from(attestation: NvidiaAttestationV1) -> Result<Self, String> {
        let certificates = attestation
            .certificates
            .iter()
            .map(|cert| der_to_pem(cert.as_bytes(), PEM_CERTIFICATE))
            .collect::<Vec<_>>()
            .join("")
            .into_bytes();

        Ok(NvidiaEvidence {
            report: attestation.attestation_report.into_bytes(),
            certificates,
        })
    }
}
