[package]
name = "attestation"
description = "Attestation functionality for dcap, nvidia, sev, and tpm-snp attestation"
version = "0.1.0"
authors = ["Fortanix, Inc."]
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/fortanix/attestation"

[dependencies]
der = { workspace = true, features = ["alloc", "derive", "oid", "pem"] }
log = { workspace = true }
mbedtls = { workspace = true, features = ["std", "time"] }
nvml = { workspace = true, optional = true }
pkix = {workspace = true}
serde = { workspace = true, features = ["derive"] }
sgx-isa = { workspace = true, default-features = true }
sgx_pkix = {workspace = true}
thiserror = { workspace = true }
yasna = { workspace = true, features = ["num-bigint", "bit-vec"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
tdx-ql = { workspace = true, optional = true }

[features]
nvidia-evidence = ["nvml"]
tdx = []
tdx-guest = ["tdx","dep:tdx-ql"]

[[example]]
name = "tdreport_tool"
path = "src/tdx/tests/tdreport_tool.rs"